DROP TABLE IF EXISTS user;
CREATE TABLE user
(
    id   INT(11) NOT NULL,
    username VARCHAR(50) NULL DEFAULT NULL,
    password VARCHAR(50) NULL DEFAULT NULL,
    firstname VARCHAR(50) NULL DEFAULT NULL,
    lastname VARCHAR(50) NULL DEFAULT NULL,
    email VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
);
